version: '3.8'

name: my-local

x-labels: &network
  networks:
    - my-net

services:
  main:
    image: &main-image main-local:latest
    build: &built-main-image
      context: .
      dockerfile: Dockerfile
    container_name: main-local
    hostname: main-local
    restart: always
    # volumes: &main-volumes
    #   - ./backend:/backend
    depends_on:
      redis:
        condition: service_started
      # main-init:
      #   condition: service_completed_successfully
    env_file: .env
    # command: bash -c 'scripts/start-main.sh'
    ports:
      - 8000:8000
    <<: *network

  # main-init:
  #   image: *main-image
  #   build: *built-main-image
  #   container_name: main-init-local
  #   hostname: main-init-local
  #   restart: "no"
  #   # volumes: *main-volumes
  #   env_file: .env
  #   command: bash -c 'python scripts/compile.py'
  #   <<: *network

  redis:
    image: bitnami/redis:7.2.4
    container_name: redis-local
    hostname: redis-local
    ports:
      - 6379:6379
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_AOF_ENABLED=no
    volumes:
      - redis:/bitnami/redis/data
    <<: *network

volumes:
  redis:
    name: redis-local

networks:
  my-net:
    name: my-net